var f = new autoLink();
f.add(&quot;wisata&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;pesawat&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;destinasi&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;liburan&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;perjalanan&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;Hayukjalan.com&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;maskapai&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;penerbangan&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;appetizer&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;main course&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;dessert&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;hotel&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;kamar&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;traveler&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;berwisata&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;pariwisata&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;eksotis&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;alam&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;bahari&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;budaya&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;sejarah&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.add(&quot;kuliner&quot;, &quot;https://www.hayukjalan.com/&quot;);
f.startScript();